disabled_rules:
  - trailing_whitespace
  - blanket_disable_command
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - empty_count
  - missing_docs
line_length:
  warning: 150
  error: 200
excluded:
  - Pods
  - Generated
  - .build
